export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST';
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS';
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL';

export const ADDRESS_SAVE_REQUEST = 'ADDRESS_SAVE_REQUEST';
export const ADDRESS_SAVE_SUCCESS = 'ADDRESS_SAVE_SUCCESS';
export const ADDRESS_SAVE_FAIL = 'ADDRESS_SAVE_FAIL';

export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST';
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL';
